create table if not exists public.certificate_templates (
  id int generated by default as identity primary key,
  code text not null unique,
  html_template text not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_certificate_templates_set_updated_at on public.certificate_templates;
create trigger trg_certificate_templates_set_updated_at
before update on public.certificate_templates
for each row execute function public.set_updated_at();

