create extension if not exists pgcrypto;

do $$ begin
  create type public.user_status as enum ('ACTIVE', 'LOCKED', 'DELETED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.track_status as enum ('HIDDEN', 'PUBLISHED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.certificate_status as enum ('ACTIVE');
exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  full_name text not null,
  status public.user_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_users_set_updated_at on public.users;
create trigger trg_users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create table if not exists public.roles (
  id int generated by default as identity primary key,
  code text not null unique,
  name text not null
);

create table if not exists public.user_roles (
  user_id uuid not null references public.users(id) on delete cascade,
  role_id int not null references public.roles(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table if not exists public.tracks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  artist_id uuid not null references public.users(id) on delete restrict,
  author_name text,
  genre text,
  duration int,
  status public.track_status not null default 'HIDDEN',
  usage_rights text[] not null default '{}'::text[],
  original_audio_key text,
  preview_audio_key text,
  created_by uuid not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_tracks_set_updated_at on public.tracks;
create trigger trg_tracks_set_updated_at
before update on public.tracks
for each row execute function public.set_updated_at();

create index if not exists idx_tracks_status on public.tracks(status);
create index if not exists idx_tracks_genre on public.tracks(genre);
create index if not exists idx_tracks_artist_id on public.tracks(artist_id);
create index if not exists idx_tracks_usage_rights_gin on public.tracks using gin (usage_rights);

create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  track_id uuid not null references public.tracks(id) on delete restrict,
  buyer_id uuid not null references public.users(id) on delete restrict,
  artist_id uuid not null references public.users(id) on delete restrict,
  selected_usage_rights text[] not null default '{}'::text[],
  track_snapshot_name text not null,
  buyer_snapshot_name text not null,
  artist_snapshot_name text not null,
  pdf_file_key text not null,
  status public.certificate_status not null default 'ACTIVE',
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_certificates_track_id on public.certificates(track_id);
create index if not exists idx_certificates_buyer_id on public.certificates(buyer_id);
create index if not exists idx_certificates_artist_id on public.certificates(artist_id);
create index if not exists idx_certificates_created_at on public.certificates(created_at);

insert into public.roles (code, name) values
  ('SUPER_ADMIN', 'Super Admin'),
  ('ADMIN', 'Admin'),
  ('ARTIST', 'Artist'),
  ('BUYER', 'Buyer')
on conflict (code) do nothing;